version: '3.9'
services:
    postgres:
      image: postgres:12-alpine
      restart: always
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=secret
        - POSTGRES_USER=root
        - POSTGRES_DB=simple_bank
    api:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      ports:
        - 8080:8080
      depends_on:
        - postgres
      environment:
        - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable