apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::565869887733:role/ECR_access_role
      rolename: role-to-assume
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::565869887733:user/github-ci
      username: github-ci