name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: root
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: Check out code into Go module directory   
      uses: actions/checkout@v3

    - name: Install Golang migrate
      run: |
      curl -L https://github.com/golang-migrate/migrate/releases/download/$version/migrate.$migrate.linux-386.tar.gz | tar xvz 
      sudo mv migrate.linux-386 /usr/bin/migrate
      which migrate

    - name: Do DB migration   
      run: make migrateup

    - name: Test
      run: make test
