# name of the test
name: ci-test

# how and what we trigger to run the test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
# DB service linked with the workflow
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_USER: root
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: Check out code into Go module directory   
      uses: actions/checkout@v3

# install migrate CLI
    - name: Install Golang migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-386.tar.gz | tar xvz 
# move the binary file to /usr/bin/ folder 
        sudo mv migrate /usr/bin/ 
        which migrate
# migrate the DB schema to the newly launched container
    - name: Do DB migration   
      run: make migrateup
# launch the test
    - name: Test
      run: make test
